fix: Allow `children` to accept `ReactNode`
Fixes error when using multiple children:

```
error TS2746: This JSX tag's 'children' prop expects a single child of type 'ReactElement<any, string | JSXElementConstructor<any>> | undefined', but multiple children were provided.
```